SELECT 
    P.PRODUCT_NAME,
    SUM(O.UNIT) AS UNIT
FROM PRODUCTS P
JOIN ORDERS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.ORDER_DATE >= '2020-02-01'
  AND O.ORDER_DATE < '2020-03-01'
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
HAVING SUM(O.UNIT) >= 100;